language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - glpk-utils
    - gcc-4.8
    - g++-4.8
git:
  submodules: false
before_install:
  - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq
  - sudo apt-get install -qq python-pygraphviz
  - sudo apt-get install -qq g++-4.8 libstdc++-4.8-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - export CXX="g++-4.8" CC="gcc-4.8"
  - echo "CXX=$CXX"
  - echo "version `$CXX --version`"
install:
  - pip install pygraphviz
  - pip install -r requirements.txt
  - pip install .
script:
  - cd examples
  - py.test -v --cov pyvpsolver
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls || echo "failed"; fi
